version: "3"
services:
#  hmpps-find-and-refer-an-intervention-service:
#    build:
#      context: .
#    networks:
#      - hmpps
#    container_name: hmpps-find-and-refer-an-intervention-service
#    ports:
#      - "8080:8080"
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
#    environment:
#      - SERVER_PORT=8080
#      - HMPPS_AUTH_URL=http://hmpps-auth:8080/auth
#      - SPRING_PROFILES_ACTIVE=dev
#      -

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./src/main/resources/db/local/init:/docker-entrypoint-initdb.d:ro

  hmpps-auth:
    image: quay.io/hmpps/hmpps-auth:latest
    networks:
      - hmpps
    container_name: hmpps-auth
    ports:
      - "8090:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth/health"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - APPLICATION_AUTHENTICATION_UI_ALLOWLIST=0.0.0.0/0

networks:
  hmpps:
