apiVersion: batch/v1
kind: CronJob
metadata:
  name: load-interventions
spec:
  schedule: "30 3 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: "Never"
          containers:
            - name: load-interventions
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: Always
              args: ["--jobName=loadInterventionCatalogueMapJob"]
{{- include "deployment.envs" . | nindent 14 }}