hmpps-auth:
  url: "http://localhost:8090/auth"

postgres:
  uri: localhost:5433
  db: findandrefer
  username: postgres
  password: password

spring:
  flyway:
    locations: classpath:db/migration,classpath:db/local
    clean-on-validation-error: true
    clean-disabled: false

# example client configuration for calling out to other services
# TODO: Remove / replace this configuration
example-api:
  url: "http://localhost:8080"
  client:
    id: "example-api-client"
    secret: "example-api-client-secret"
