hmpps-auth:
  baseurl: "http://hmpps-auth:9090/auth"

spring:
  jpa:
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  flyway:
    locations: classpath:db/migration,classpath:db/local
    clean-disabled: false
  security:
    oauth2:
      client:
        registration:
          find-and-refer-interventions-client:
            client-id: hmpps-find-and-refer-an-intervention-ui-client
            client-secret: clientsecret

find-and-refer-and-delius:
  baseurl: "http://localhost:9092"

hmpps.sqs:
  provider: localstack
  queues:
    hmppsdomaineventsqueue:
      queueName: hmppsdomainevent
      dlqName: ${random.uuid}
      subscribeTopicId: hmppseventtopic
      subscribeFilter: '{"eventType":[ "probation-case.requirement.created", "probation-case.licence-condition.created" ]}'
  topics:
    hmppseventtopic:
      arn: arn:aws:sns:eu-west-2:000000000000:hmppseventstopic
