hmpps-auth:
  url: "http://localhost:9090/auth"

postgres:
  db: findandrefer
  username: root
  password: dev

spring:
  flyway:
    locations: classpath:db/migration,classpath:db/local
    clean-on-validation-error: true
    clean-disabled: false
