hmpps-auth:
  baseurl: "http://hmpps-auth:9090/auth"

spring:
  jpa:
    properties:
      hibernate:
        format_sql: false
    show-sql: false
  flyway:
    locations: classpath:db/migration,classpath:db/local
    clean-disabled: false
  security:
    oauth2:
      client:
        registration:
          find-and-refer-interventions-client:
            client-id: hmpps-find-and-refer-an-intervention-ui-client
            client-secret: clientsecret

find-and-refer-and-delius:
  baseurl: "http://localhost:9092"

hmpps:
  sqs:
    provider: localstack
    queues:
      hmppsdomaineventsqueue:
        queueName: hmpps_domain_events_queue
        dlqName: hmpps_domain_events_dlq
        subscribeTopicId: hmppsdomaineventstopic
        subscribeFilter: '{"eventType":[ "probation-case.requirement.created", "probation-case.liccondition.created" ]}'
        asyncQueueClient: true
    topics:
      hmppsdomaineventstopic:
        arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}
