version: 2.1
orbs:
  hmpps: ministryofjustice/hmpps@10
  mem: circleci/rememborb@0.0.2
parameters:
  releases-slack-channel:
    type: string
    default: find-refer-interventions-dev-notification

jobs:
  validate:
    executor:
      name: hmpps/java_postgres
      jdk_tag: "21.0"
      postgres_tag: "16.1"

    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - run:
          name: Validate metadata
          command: |
            script/validate-metadata.sh
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - hmpps/database_schema_report:
          schema: "public"
          initialise_database: "./gradlew check"
          filters:
            branches:
              only:
                - main
      - validate:
          filters:
            tags:
              ignore: /.*/
      - hmpps/helm_lint:
          name: helm_lint
      - hmpps/build_multiplatform_docker:
          name: build_docker
          filters:
            branches:
              only:
                - main
      - hmpps/deploy_env:
          name: deploy_dev
          env: "dev"
          jira_update: true
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - validate
            - build_docker
            - helm_lint
          helm_timeout: 5m
      - hmpps/deploy_env:
          name: deploy_preprod
          env: "preprod"
          jira_update: true
          jira_env_type: staging
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          context:
            - hmpps-common-vars
            - hmpps-find-and-refer-an-intervention-preprod-deploy
          helm_timeout: 5m
          requires:
            - deploy_dev
      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: "prod"
          jira_update: true
          jira_env_type: production
          pipeline_id: <<pipeline.id>>
          pipeline_number: <<pipeline.number>>
          slack_notification: true
          slack_channel_name: << pipeline.parameters.releases-slack-channel >>
          context:
            - hmpps-common-vars
            - hmpps-find-and-refer-an-intervention-prod-deploy
          requires:
            - request-prod-approval
          helm_timeout: 5m
