INSERT INTO pdu_ref(id, name, pcc_region_id)
VALUES ('redcar-cleveland-and-middlesbrough', 'Redcar, Cleveland and Middlesbrough', 'cleveland')
     , ('stockton-and-hartlepool', 'Stockton and Hartlepool', 'cleveland')
     , ('county-durham-and-darlington', 'County Durham and Darlington', 'durham')
     , ('newcastle-upon-tyne', 'Newcastle Upon Tyne', 'northumbria')
     , ('gateshead-and-south-tyneside', 'Gateshead and South Tyneside', 'northumbria')
     , ('sunderland', 'Sunderland', 'northumbria')
     , ('north-tyneside-and-northumberland', 'North Tyneside and Northumberland', 'northumbria')
     , ('warrington-and-halton', 'Warrington and Halton', 'cheshire')
     , ('cheshire-east', 'Cheshire East', 'cheshire')
     , ('cheshire-west', 'Cheshire West', 'cheshire')
     , ('cumbria', 'Cumbria', 'cumbria')
     , ('blackburn', 'Blackburn', 'lancashire')
     , ('east-lancashire', 'East Lancashire', 'lancashire')
     , ('central-lancashire', 'Central Lancashire', 'lancashire')
     , ('north-west-lancashire', 'North West Lancashire', 'lancashire')
     , ('liverpool-north', 'Liverpool North', 'merseyside')
     , ('liverpool-south', 'Liverpool South', 'merseyside')
     , ('knowsley-and-st-helens', 'Knowsley and St Helens', 'merseyside')
     , ('sefton', 'Sefton', 'merseyside')
     , ('wirral', 'Wirral', 'merseyside')
     , ('hull-and-east-riding', 'Hull and East Riding', 'humberside')
     , ('north-and-north-east-lincolnshire', 'North and North East Lincolnshire', 'humberside')
     , ('north-yorkshire', 'North Yorkshire', 'north-yorkshire')
     , ('barnsley-and-rotherham', 'Barnsley and Rotherham', 'south-yorkshire')
     , ('doncaster', 'Doncaster', 'south-yorkshire')
     , ('sheffield', 'Sheffield', 'south-yorkshire')
     , ('bradford-and-calderdale', 'Bradford and Calderdale', 'west-yorkshire')
     , ('kirklees', 'Kirklees', 'west-yorkshire')
     , ('leeds', 'Leeds', 'west-yorkshire')
     , ('wakefield', 'Wakefield', 'west-yorkshire')
     , ('york', 'York', 'west-yorkshire')
     , ('dyfed-powys', 'Dyfed Powys', 'dyfed-powys')
     , ('gwent', 'Gwent', 'gwent')
     , ('north-wales', 'North Wales', 'north-wales')
     , ('swansea-neath-and-port-talbot', 'Swansea, Neath and Port Talbot', 'south-wales')
     , ('cardiff-and-the-vale', 'Cardiff and the Vale', 'south-wales')
     , ('cwm-taf-morgannwg', 'Cwm Taf Morgannwg', 'south-wales')
     , ('staffordshire-and-stoke', 'Staffordshire and Stoke', 'staffordshire')
     , ('warwickshire', 'Warwickshire', 'warwickshire')
     , ('herefordshire-shropshire-and-telford', 'Herefordshire, Shropshire and Telford', 'west-mercia')
     , ('worcestershire', 'Worcestershire', 'west-mercia')
     , ('birmingham-central-and-south', 'Birmingham Central and South', 'west-midlands')
     , ('birmingham-north-east-and-solihull', 'Birmingham North, East and Solihull', 'west-midlands')
     , ('coventry', 'Coventry', 'west-midlands')
     , ('dudley-and-sandwell', 'Dudley and Sandwell', 'west-midlands')
     , ('walsall-and-wolverhampton', 'Walsall and Wolverhampton', 'west-midlands')
     , ('derby-city', 'Derby City', 'derbyshire')
     , ('derbyshire', 'Derbyshire', 'derbyshire')
     , ('leicester-leicestershire-and-rutland', 'Leicester, Leicestershire and Rutland', 'leicestershire')
     , ('east-and-west-lincolnshire', 'East and West Lincolnshire', 'lincolnshire')
     , ('nottingham-city', 'Nottingham City', 'nottinghamshire')
     , ('nottinghamshire', 'Nottinghamshire', 'nottinghamshire')
     , ('bath-and-north-somerset', 'Bath and North Somerset', 'avon-and-somerset')
     , ('bristol-and-south-gloucestershire', 'Bristol and South Gloucestershire', 'avon-and-somerset')
     , ('somerset', 'Somerset', 'avon-and-somerset')
     , ('cornwall-and-isles-of-scilly', 'Cornwall and Isles of Scilly', 'devon-and-cornwall')
     , ('devon-and-torbay', 'Devon and Torbay', 'devon-and-cornwall')
     , ('plymouth', 'Plymouth', 'devon-and-cornwall')
     , ('dorset', 'Dorset', 'dorset')
     , ('gloucestershire', 'Gloucestershire', 'gloucestershire')
     , ('swindon-and-wiltshire', 'Swindon and Wiltshire', 'wiltshire')
     , ('hampshire-north-and-east', 'Hampshire North and East', 'hampshire')
     , ('portsmouth-and-isle-of-wight', 'Portsmouth and Isle of Wight', 'hampshire')
     , ('southampton-eastleigh-and-new-forest', 'Southampton, Eastleigh and New Forest', 'hampshire')
     , ('buckinghamshire-and-milton-keynes', 'Buckinghamshire and Milton Keynes', 'thames-valley')
     , ('east-berkshire', 'East Berkshire', 'thames-valley')
     , ('west-berkshire', 'West Berkshire', 'thames-valley')
     , ('oxfordshire', 'Oxfordshire', 'thames-valley')
     , ('bedfordshire', 'Bedfordshire', 'bedfordshire')
     , ('cambridgeshire', 'Cambridgeshire', 'cambridgeshire')
     , ('essex-north', 'Essex North', 'essex')
     , ('essex-south', 'Essex South', 'essex')
     , ('hertfordshire', 'Hertfordshire', 'hertfordshire')
     , ('norfolk', 'Norfolk', 'norfolk')
     , ('northamptonshire', 'Northamptonshire', 'northamptonshire')
     , ('suffolk', 'Suffolk', 'suffolk')
     , ('barking-dagenham-and-havering', 'Barking, Dagenham and Havering', 'metropolitan')
     , ('brent', 'Brent', 'metropolitan')
     , ('camden-and-islington', 'Camden and Islington', 'metropolitan')
     , ('croydon', 'Croydon', 'metropolitan')
     , ('ealing-and-hillingdon', 'Ealing and Hillingdon', 'metropolitan')
     , ('enfield-and-haringey', 'Enfield and Haringey', 'metropolitan')
     , ('greenwich-and-bexley', 'Greenwich and Bexley', 'metropolitan')
     , ('hackney-and-city', 'Hackney and City', 'metropolitan')
     , ('hammersmith-fulham-kensington-chelsea-and-westminster',
        'Hammersmith, Fulham, Kensington, Chelsea and Westminster', 'metropolitan')
     , ('harrow-and-barnet', 'Harrow and Barnet', 'metropolitan')
     , ('kingston-richmond-and-hounslow', 'Kingston, Richmond and Hounslow', 'metropolitan')
     , ('lambeth', 'Lambeth', 'metropolitan')
     , ('lewisham-and-bromley', 'Lewisham and Bromley', 'metropolitan')
     , ('newham', 'Newham', 'metropolitan')
     , ('redbridge-and-waltham-forest', 'Redbridge and Waltham Forest', 'metropolitan')
     , ('southwark', 'Southwark', 'metropolitan')
     , ('tower-hamlets', 'Tower Hamlets', 'metropolitan')
     , ('wandsworth-merton-and-sutton', 'Wandsworth, Merton and Sutton', 'metropolitan')
     , ('east-kent', 'East Kent', 'kent')
     , ('west-kent', 'West Kent', 'kent')
     , ('surrey', 'Surrey', 'surrey')
     , ('east-sussex', 'East Sussex', 'sussex')
     , ('west-sussex', 'West Sussex', 'sussex')
     , ('bolton', 'Bolton', 'greater-manchester')
     , ('bury-and-rochdale', 'Bury and Rochdale', 'greater-manchester')
     , ('manchester-north', 'Manchester North', 'greater-manchester')
     , ('manchester-south', 'Manchester South', 'greater-manchester')
     , ('oldham', 'Oldham', 'greater-manchester')
     , ('salford', 'Salford', 'greater-manchester')
     , ('stockport-and-trafford', 'Stockport and Trafford', 'greater-manchester')
     , ('tameside', 'Tameside', 'greater-manchester')
     , ('wigan', 'Wigan', 'greater-manchester');
