INSERT INTO risk_consideration (id, intervention_id, cn_score_guide, extremism_risk_guide, sara_partner_score_guide,
                                sara_other_score_guide, osp_score_guide,osp_dc_icc_combination_guide, ogrs_score_guide,
                                ovp_guide, ogp_guide, pna_guide, rosh_level, rsr_guide)
VALUES ('4d139b00-60bf-4e95-ab6a-be85ed24b3c2',
        '4902a268-9907-4070-ba48-7c2870a3b77e',
        'total score of 5+ OASys items
                     2.6 - Recognises the impact and consequences of offending
                     7.2 - Regular activities encourage offending
                     11.4 - Temper control
                     11.6 - Problem solving
                     11.7 - Awareness of consequences
                     11.9 - Understands other peoplenulls point of view
                     12.1 - Pro-criminal attitudes',
        null,
        'Medium SARA (Spousal Assault Risk Assessment) in custody Medium or hgh SARA (Spousal Assault Risk Assessment) in the community',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        'MEDIUM',
        null),
       ('0127b47f-af04-4d0a-91ce-45dd666d31eb',
        'd61fc961-243e-4321-bafb-5d71e1fd13a4',
        null,
        '22+ ERG',
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        'Yes',
        null,
        null),
       ('45a1de12-e419-443f-990e-3a9fee6027f6',
        '432b2353-b794-4b12-8018-6c7ede6a1ed6',
        null,
        null,
        null,
        null,
        'Medium, high or very high',
        null,
        null,
        null,
        null,
        'Yes',
        null,
        null),
       ('262f1e6c-8b7d-42dc-84c8-cca5cd585f89',
        'a6c18ff3-83bd-4ad2-bcbe-1db3fb55a341',
        null,
        null,
        null,
        null,
        'Medium, high or very high',
        null,
        null,
        null,
        null,
        'Yes',
        null,
        null),
       ('aa981597-023b-404b-8d64-7efedaecc423',
        '94af0e1f-f55f-4422-afc5-536178c63b5f',
        null,
        null,
        null,
        null,
        null,
        null,
        '50+ over 2 years',
        null,
        null,
        null,
        null,
        null);
