apiVersion: batch/v1
kind: CronJob
metadata:
  name: load-delivery-location
spec:
  schedule: "0 3 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: "Never"
          containers:
            - name: load-delivery-location
              image: quay.io/hmpps/hmpps-find-and-refer-an-intervention-service:latest
              imagePullPolicy: Always
              args: ["--jobName=loadDeliveryLocationJob"]
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - "ALL"
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
{{- include "deployment.envs" . | nindent 14 }}