apiVersion: batch/v1
kind: CronJob
metadata:
  name: load-interventions-catalogue-to-course-map
spec:
  schedule: "0 4 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: "Never"
          containers:
            - name: load-interventions-catalogue-to-course-map
              image: quay.io/hmpps/hmpps-find-and-refer-an-intervention-service:latest
              imagePullPolicy: Always
              args: ["--jobName=loadInterventionCatalogueToCourseMapJob"]
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - "ALL"
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
  {{- include "deployment.envs" (index .Values "generic-service") | nindent 14 }}