---
generic-service:

  # Per environment values which override defaults in hmpps-template-kotlin/values.yaml

  replicaCount: 2

  ingress:
    enabled: true
    host: find-and-refer-intervention-api.hmpps.service.justice.gov.uk
    migration:
      colour: green

  env_details:
    contains_live_data: true

  image:
    repository: quay.io/hmpps/hmpps-find-and-refer-an-intervention-service
    tag: latest
    port: 8080

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.prod.json"
    HMPPS_AUTH_BASEURL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    FIND_AND_REFER_AND_DELIUS_BASEURL: "https://find-and-refer-and-delius.hmpps.service.justice.gov.uk"
    API_BASEURL_FIND_AND_REFER: "https://find-and-refer-intervention-api.hmpps.service.justice.gov.uk"
    SENTRY_ENVIRONMENT: prod

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: PROD_ALERTS_SEVERITY_LABEL
