---
# Per environment values which override defaults in hmpps-template-kotlin/values.yaml

replicaCount: 2

ingress:
  enabled: true
  host: find-and-refer-intervention-api.hmpps.service.justice.gov.uk
  migration:
    colour: green

env_details:
  contains_live_data: true

image:
  repository: quay.io/hmpps/hmpps-find-and-refer-an-intervention-service
  tag: latest
  port: 8080

env:
  APPLICATIONINSIGHTS_CONFIGURATION_FILE: "applicationinsights.prod.json"
  HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
  # Template kotlin calls out to itself to provide an example of a service call
  # TODO: This should be replaced by a call to a different service, or removed
  # EXAMPLE_API_URL: "https://template-kotlin-prod.hmpps.service.justice.gov.uk"

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: PROD_ALERTS_SEVERITY_LABEL
