INSERT INTO service_provider (id, name) 
VALUES  ('FOUNDATION', 'Foundation'),
        ('LANCASHIRE_WOMEN', 'Lancashire Women'),
        ('LINCS_ACTION_TRUST', 'Lincolnshire Action Trust'),
        ('MAXIMUS_UK', 'MAXIMUS UK Services Limited'),
        ('NACRO', 'Nacro'),
        ('NOTT_WOMENS_CENTRE', 'Nottingham Women''s Centre'),
        ('PSS_UK', 'PSS UK'),
        ('SEETEC_BUS_TECH_CTR_LTD', 'Seetec Business Technology Centre Limited'),
        ('SHELTER', 'Shelter'),
        ('ST_GILES_WISE_GRP', 'St Giles Wise Group Partnership'),
        ('WOMENS_COMM_MATTERS', 'Women''s Community Matters'),
        ('WOMENS_WORK_DERBS_LTD', 'Women''s Work (Derbyshire) Ltd'),
        ('ANAWIM', 'Anawim'),
        ('AIR_SPORTS_NETWORK_LTD', 'AIR Sports Network Ltd'),
        ('ALLIANCE_SPORT', 'Alliance of Sport'),
        ('ANGLIA_CARE_TRUST', 'Anglia Care Trust (ACT)'),
        ('AURORA_NEW_DAWN', 'Aurora New Dawn'),
        ('BEDFORD_WOMENS_CENTRE', 'Bedford Women''s Centre'),
        ('BIRTH_COMPANIONS', 'Birth Companions'),
        ('BLACK_COUNTRY_WA', 'Black Country Women''s Aid'),
        ('C2C', 'C2C'),
        ('CAIS_LTD', 'CAIS Ltd'),
        ('CAMBS_WMNS_RESOURCE_CTR', 'Cambridge Women''s Resource Centre'),
        ('CHANGE_GROW_LIVE_LTD', 'Change Grow Live (CGL) Services Ltd'),
        ('CIRCLES_UK', 'Circles UK'),
        ('COMMUNITY_LED_INIT', 'Community Led Initiatives'),
        ('DVIP_RICHMOND', 'DVIP (Richmond Fellowship)'),
        ('EVOLVE_EAST_ANGLIA', 'Evolve East Anglia'),
        ('GANGSLINE', 'Gangsline'),
        ('GROUNDWORK_EAST', 'Groundwork East'),
        ('GROW', 'Grow'),
        ('HIBISCUS_INIT', 'Hibiscus Initiatives'),
        ('HUMANKIND', 'HumanKind'),
        ('INCLUSION', 'Inclusion'),
        ('IDAS', 'Independent Domestic Abuse Service (IDAS)'),
        ('INSPIRE_CUMBRIA_LTD', 'Inspira Cumbria Ltd'),
        ('JUDAH_ARMANI', 'Judah Armani Public Service Design Practice'),
        ('KALEIDOSCOPE', 'Kaleidoscope'),
        ('KAREN_MACKEY', 'Karen Mackey Consultants'),
        ('KSS_CRC', 'Kent, Surrey and Sussex CRC'),
        ('KHIDMAT_CENTRE', 'Khidmat Centre'),
        ('LEONARD_CHESHIRE', 'Leonard Cheshire Disability'),
        ('MAGISTRA', 'Magistra'),
        ('NEPACS', 'Nepacs'),
        ('OFFPLOY', 'Offploy CIC'),
        ('ORMISTON_FAMILIES', 'Ormiston Families'),
        ('PACT', 'PACT'),
        ('PACT_FUTURES_CIC', 'PACT Futures Community Interest Company'),
        ('REFORM_RESTORE_RESPECT', 'Reform,Restore,Respect'),
        ('RESTORATIVE_WALES', 'Restorative Wales'),
        ('RETHINK_MI_LTD', 'Rethink Mental Illness Ltd'),
        ('RFEA', 'RFEA'),
        ('RISE_MUTUAL_CIC', 'RISE Mutual CIC'),
        ('SAFE_GROUND', 'Safe Ground'),
        ('SHP', 'SHP'),
        ('SPARK_INSIDE', 'Spark Inside'),
        ('ST_GILES_TRUST', 'St Giles Trust'),
        ('SUSSEX_PATHWAYS', 'Sussex Pathways'),
        ('THAMES_VALLEY_PART', 'Thames Valley Partnership'),
        ('THE_BRIDGE_EM', 'The Bridge (East Midlands)'),
        ('THE_WISE_GROUP_LTD', 'The Wise Group Limited'),
        ('TOMORROWS_WOMEN_WIRRAL', 'Tomorrow''s Women Wirral'),
        ('TOUCHSTONE_LEEDS', 'Touchstone - Leeds'),
        ('UP_BEAT_LIFE', 'Up Beat Life'),
        ('WORKING_CHANCE_LTD', 'Working Chance Ltd'),
        ('YSS', 'YSS'),
        ('GATEWAY_4_WOMEN', 'Gateway 4 Women'),
        ('WOMEN_OUT_WEST', 'Women Out West'),
        ('PLUSS_ORG_CIC', 'The Pluss Organisation CIC'),
        ('STEPPINGSTONES_LUTON', 'Stepping Stones (Luton)'),
        ('SAFER_PLACES', 'Safer Places'),
        ('ONE_SMALL_THING', 'One Small Thing'),
        ('RISING_SUN_DVA', 'Rising Sun Domestic Violence and Abuse Service'),
        ('A_WAY_OUT', 'A Way Out'),
        ('NEWDAWN_NEWDAY', 'New Dawn New Day'),
        ('ACCORD_HOUSING_ASSOC', 'Accord Housing Association'),
        ('WOMENSSUPPORTCTR_SURREY', 'Women''s Support Centre Surrey'),
        ('GM_WOM_SUP_AL', 'Greater Manchester Women''s Support Alliance'),
        ('GM_MH_NHS_FT', 'Greater Manchester Mental Health NHS Foundation Trust - Achieve Recovery Services'),
        ('ROAR_TURNING_POINT', 'ROAR Turning Point'),
        ('PENNINE_CARE_NHS_FT', 'Pennine Care NHS Foundation Trust - Pathfinder Stockport'),
        ('WITH_YOU_WIGAN_LEIGH', 'With You - Wigan and Leigh'),
        ('JIGSAW_SUPPORT', 'Jigsaw Support'),
        ('POPS', 'Partners of Prisoners and Families Support Group (POPS)'),
        ('PETRUS_COMMUNITY', 'Petrus Community'),
        ('SALFORD_FOUNDATION', 'Salford Foundation Limited'),
        ('URBAN_OUTREACH', 'Urban Outreach Bolton'),
        ('WOMEN_FOR_WELL_WOMEN', 'Women for Well Women'),
        ('WOMEN_OF_WORTH', 'Women of Worth'),
        ('STOCKPORT_WOMENS_CENTRE', 'Stockport Women''s Centre'),
        ('MANCHESTER_ATHENA', 'Manchester Athena'),
        ('ACORN', 'Acorn'),
        ('BIRMINGHAM_SETTLEMENT', 'Birmingham Settlement'),
        ('ADFERIAD', 'Adferiad Recovery Limited'),
        ('ST_GILES_WISE_LTD', 'St Giles Wise Ltd'),
        ('ACHIEVE_NW', 'Achieve'),
        ('ADVANCE_CHARITY', 'Advance Charity'),
        ('BWC', 'BWC (Brighton Women''s Centre)'),
        ('CATCH_22_CHARITY_LTD', 'Catch22 Charity Limited'),
        ('CHANGING_LIVES', 'Changing Lives'),
        ('INGEUS_UK_LIMITED', 'Ingeus UK Limited'),
        ('ST_MUNGOS', 'St Mungos'),
        ('THE_FORWARD_TRUST', 'The Forward Trust'),
        ('WOMEN_IN_PRISON', 'Women in Prison'),
        ('THE_GROWTH_COMPANY_LTD', 'The Growth Company Ltd'),
        ('THE_NELSON_TRUST', 'The Nelson Trust'),
        ('WOMENS_CTR_CORNWALL', 'The Women’s Centre Cornwall (TWCC)'),
        ('THIRTEEN_HOUSING_GROUP', 'Thirteen Housing Group'),
        ('TOGETHER_WOMEN_PROJECT', 'Together Women Project'),
        ('WILLOWDENE', 'Willowdene Rehabilitation and Training'),
        ('CHOICES', 'Choices'),
        ('PRISON_ADVICE_CARE_TRST', 'Prison Advice and Care Trust (Pact)'),
        ('ACCESS_2_ADVICE', 'Access 2 Advice'),
        ('STEPCHANGE_DEBT_CHARITY', 'StepChange Debt Charity'),
        ('IMO_CHARITY', 'IMO Charity'),
        ('ROTUNDA', 'Rotunda'),
        ('HOUSING_4_WOMEN', 'Housing 4 Women'),
        ('CLEAN_BREAK', 'Clean Break'),
        ('INSPIRIT_T_D', 'Inspirit Training and Development Ltd'),
        ('PECAN', 'Pecan'),
        ('WE_ARE_WITH_YOU', 'We Are With You'),
        ('BACK_ON_TRACK', 'Back On Track'),
        ('BIG_LIFE_GROUP', 'Big Life Group'),
        ('BOLTON_COMMUNITY_ADVICE', 'Bolton Community Advice'),
        ('FOUNDATION_92', 'Foundation 92'),
        ('OUT_THERE_IN_TRAFFORD', 'Out There In Trafford'),
        ('ROCHDALE_CONNECTIONS_TRUST', 'Rochdale Connections Trust'),
        ('STEPPINGSTONE_BURY', 'Stepping Stone (Bury)'),
        ('POSITIVE_STEPS', 'Positive Steps'),
        ('ROCHDALE_CONNECTIONS_TR', 'Rochdale Connections Trust');
